Repository ucsb-cs156-s25/proj-rec-s25-13, pull requests merged in 2025-05, with the labels that each got.

#24 kenneth - changed default of student to true
  src/main/java/edu/ucsb/cs156/rec/entities/User.java
Labels: 5, Merge Candidate-CI

#31 Tuan student removal
  frontend/src/fixtures/currentUserFixtures.js
  frontend/src/fixtures/usersFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/components/Users/UsersTable.test.js
  src/main/java/edu/ucsb/cs156/rec/config/SecurityConfig.java
  src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
  src/main/java/edu/ucsb/cs156/rec/entities/User.java
  src/main/java/edu/ucsb/cs156/rec/interceptors/RoleInterceptor.java
  src/test/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestTests.java
  src/test/java/edu/ucsb/cs156/rec/interceptors/RoleInterceptorTests.java
Labels: 10, Merge Candidate-CI

#35 timothy - added admin get all requests + tests
  src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
  src/test/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestControllerTest.java
Labels: 10, Merge Candidate-CI

#33 connersiou - added rec req table to pending requests page
  frontend/src/main/pages/Requests/PendingRequestsPage.js
  frontend/src/stories/pages/Requests/PendingRequestsPage.stories.js
  frontend/src/tests/pages/Requests/PendingRequestsPage.test.js
Labels: 10, Merge Candidate-CI

#37 Timothy - admin req page
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/AdminRequestsPage.js
  frontend/src/tests/pages/AdminRequestsPage.test.js
Labels: 10

#38 kenneth - added coverage for usertable tests
  frontend/src/tests/components/Users/UsersTable.test.js
Labels: 5, Merge Candidate-CI

#34 RequestTypeForm
  frontend/src/fixtures/requestTypeFixtures.js
  frontend/src/main/components/RequestType/RequestTypeForm.js
  frontend/src/main/utils/RequestTypeUtils.js
  frontend/src/stories/components/RequestType/RequestTypeForm.stories.js
  frontend/src/tests/components/RequestType/RequestTypeForm.test.js
  frontend/src/tests/utils/RequestTypeUtils.test.js
Labels: 10, Merge Candidate-CI

#41 kenneth - changed the frontend for datetime values
  frontend/src/fixtures/recommendationRequestFixtures.js
  frontend/src/main/components/RecommendationRequest/RecommendationRequestTable.js
  frontend/src/tests/components/RecommendationRequest/RecommendationRequestTable.test.js
Labels: 5

#40 RequestTypeTable
  frontend/src/fixtures/requestFixtures.js
  frontend/src/main/components/RequestType/RequestTypeTable.js
  frontend/src/stories/components/RequestType/RequestTypeTable.stories.js
  frontend/src/tests/components/RequestType/RequestTypeTable.test.js
Labels: 10, Merge Candidate-CI

#49 timothy - edited request controller to add completion date when request completed
  src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
  src/test/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestControllerTest.java
Labels: 10, Merge Candidate-CI

#48 connersiou - prof can update status of requests in frontend
  frontend/src/fixtures/recommendationRequestFixtures.js
  frontend/src/index.css
  frontend/src/main/components/OurTable.js
  frontend/src/main/components/RecommendationRequest/RecommendationRequestTable.js
  frontend/src/main/pages/Requests/PendingRequestsPage.js
  frontend/src/main/utils/RecommendationRequestUtils.js
  frontend/src/stories/pages/Requests/PendingRequestsPage.stories.js
  frontend/src/tests/components/OurTable.test.js
  frontend/src/tests/components/RecommendationRequest/RecommendationRequestTable.test.js
  frontend/src/tests/pages/Requests/PendingRequestsPage.test.js
  frontend/src/tests/utils/RecommendationRequestUtils.test.js
Labels: 10, Merge Candidate-CI

#53 Tuan - Nav Bar Permission Changes
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
Labels: 5, Merge Candidate-CI

#46 Implemented Request Type Pages (create/post/delete).
  frontend/src/App.js
  frontend/src/fixtures/requestFixtures.js
  frontend/src/fixtures/requestTypeFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/RequestType/RequestTypeTable.js
  frontend/src/main/pages/RequestType/RequestTypeCreatePage.js
  frontend/src/main/pages/RequestType/RequestTypeEditPage.js
  frontend/src/main/pages/RequestType/RequestTypeIndexPage.js
  frontend/src/stories/pages/RequestType/RequestTypeCreatePage.stories.js
  frontend/src/stories/pages/RequestType/RequestTypeEditPage.stories.js
  frontend/src/stories/pages/RequestType/RequestTypeIndexPage.stories.js
  frontend/src/tests/pages/RequestType/RequestTypeCreatePage.test.js
  frontend/src/tests/pages/RequestType/RequestTypeEditPage.test.js
  frontend/src/tests/pages/RequestType/RequestTypeIndexPage.test.js
  src/main/java/edu/ucsb/cs156/rec/controllers/RequestTypeController.java
Labels: 10

#51 connersiou - added a delete endpoint for professor and changed some logic
  frontend/src/fixtures/recommendationRequestFixtures.js
  frontend/src/main/components/RecommendationRequest/RecommendationRequestTable.js
  frontend/src/main/utils/RecommendationRequestUtils.js
  frontend/src/tests/components/RecommendationRequest/RecommendationRequestTable.test.js
  frontend/src/tests/utils/RecommendationRequestUtils.test.js
  src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
  src/main/java/edu/ucsb/cs156/rec/repositories/RecommendationRequestRepository.java
  src/test/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestControllerTest.java
Labels: 10, Merge Candidate-CI
